[[redirects]]
  from = "/sint"
  to = "https://priceless-turing-b02a53.netlify.app/"
  status = 200
  force = true # COMMENT: ensure that we always redirect
  headers = {X-From = "Netlify"}
  signed = "API_SIGNATURE_TOKEN"
